### ISSUE TITLE
Qualité de service > EPIC

### ISSUE THREAD

**Issue by adriens** [adriens/colisnc-api#72]
# Description

Afin de mettre en avant l'importance du monitoring d'un service, en particulier de métriques custom, nous allons enrichir cette API de ces concepts.
L'API étant simple et publique, c'est un parfait support pour des démos et de la pédagogie

# Tickets

Pour mener à bien cette EPIC, voici les tickets en lien :

- [ ] Qualité de service > Endpoints actuator #68
- [ ] Qualité de service > Front minimaliste de status #69
- [ ] Qualité de service > Démo Katacoda #70
- [ ] Qualité de service > démo intégration PagerDuty #71
